### ISSUE TITLE
Signature verification failed

### ISSUE THREAD

**Issue by netgeak** [subgraph/subgraph-os-issues#205]
When I launch torbrowser launcher after it downloads the package I get signature verification failed. I tried updating the key but it fails to find the keyserver. Is there is fix for this?
Thanks.

**Comment by dma** [comment]
This is due to this issue in Tor Browser Launcher:

https://github.com/micahflee/torbrowser-launcher/issues/260

While we wait for a new package to makes its way through Debian, there is a workaround.

1. Start Tor Browser at least once, wait for it to download, and then fail. Then cancel & exit.

2. Then run the command:

user@subgraph:~$ wget -O torkey.asc https://sks-keyservers.net/pks/lookup?op=get\&search=0x4E2C6E8793298290

This will download a recent key blob from a public key server, which you can examine if you like (see https://www.torproject.org/docs/verifying-signatures.html.en).

3. Then import the updated key blob into Tor Browser Launcher's keyring:

user@subgraph:~$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --import < torkey.asc 

You should then be able to download and verify Tor Browser using Tor Browser Launcher. If Tor Browser still fails to start, try running paxrat:

user@subgraph:~$ sudo paxrat -c /etc/paxrat/paxrat_tbl.conf

**Comment by netgeak** [comment]
That worked perfectly. Thanks!

**Comment by ZNolife** [comment]
I've got the same issue and the workaround doesn't work : The server is contacted, the request is sent, but I then receive a "404 Not Found" error.
Well, when I say "I've got" I should say "I had the same issue". I've had it 2 or 3 times but now (even before I try the workaround) every time I try to launch Tor on the alpha3, the Tor Browser window stays stuck on "Downloading signature" and after a while it says "Error starting download. Are you connected to the Internet ?". I think I'm connected to Internet (at least the wifi sign is on and Tor Network let me change identities so I guess I've got access to Internet).
I guess I'll have to wait this issue to be fixed in a next version.
Would anyone have an idea when the next version is planned ?

**Comment by dma** [comment]
I am reopening this. It's still not fixed in stretch. The workaround is here:
https://github.com/subgraph/subgraph-os-issues/issues/205#issuecomment-275866276

**Comment by mckinney-subgraph** [comment]
We released our own build of the torbrowser-launcher package today to address this issue. Running `apt-get update/upgrade`  will fetch the our new package.

**Comment by ZNolife** [comment]
I've done a "sudo apt-get update" followed by a "sudo apt-get upgrade" and after some rather long downloads (20mn) and install (may be 10mn)... but Tor Browser is still stuck when I try to launch it and, on top of that, I'm unable to get any wifi anymore (it was shutdown during the upgrade process, and I thought it was a temporary thing during the upgrade process but no... but it's probably nothing, it's just that I'm a total starter in Linux so I've no idea how to start it manualy if it's not done anymore automaticaly)
But thanks anyway for your help. I guess there must be something wrong with my install and I'd reinstall the OS next time you'll make a new ISO.

**Comment by RasmusMalver** [comment]
> I am reopening this. It's still not fixed in stretch. The workaround is here:
#205 (comment)

This did not work for me. I got the following:

    user@computer:~$ wget -O torkey.asc https://sks-keyservers.net/pks/lookup?op=get\&search=0x4E2C6E8793298290
    --2017-06-26 16:59:05--  https://sks-keyservers.net/pks/lookup?op=get&search=0x4E2C6E8793298290
    …
    user@computer:~$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --import < torkey.asc
                     gpg: key 4E2C6E8793298290: "Tor Browser Developers (signing key) <torbrowser@torproject.org>" not changed
                     gpg: Total number processed: 1
                     gpg:              unchanged: 1

I looked at `man gpg` and found a method of clearing caches. This did it for me:

    user@computer:~$ gpg --rebuild-keydb-caches
    user@computer:~$ gpg --homedir "$HOME/.local/share/torbrowser/gnupg_homedir/" --import < torkey.asc
    user@computer:~$ torbrowser-launcher

**Comment by dhksa** [comment]
@dma Hi I'm still experiencing this. After install did apt update/upgrade/dist-upgrade, hit "Download error: 404 Not Found" when I click the tor-browser icon.
Tried https://github.com/subgraph/subgraph-os-issues/issues/205#issuecomment-275866276 but still the same error. Any ideas why?
